input.onButtonPressed(Button.A, function () {
	
})
basic.showString("good night")
turtle.setPosition(2, 2)
turtle.setBrightness(255)
turtle.pen(TurtlePenMode.Down)
turtle.forward(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnRight()
turtle.forward(1)
turtle.back(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnRight()
turtle.forward(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnRight()
turtle.forward(1)
turtle.back(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnRight()
turtle.forward(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnLeft()
turtle.forward(1)
turtle.turnRight()
turtle.forward(1)
basic.forever(function () {
	
})
